name: Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Create dummy network device
        env:
          MAGMA_MAC: ${{ secrets.MAGMA_MAC }}
        shell: bash
        run: |
          sudo lsmod # loads dummy
          sudo ip link add dumdum type dummy
          sudo ifconfig dumdum hw ether "$MAGMA_MAC"


      - name: Install magma
        env:
          MAGMA_URL: ${{ secrets.MAGMA_URL }}
        shell: bash
        run: |
          wget "$MAGMA_URL" -O magma.tar.gz -o /dev/null
          tar xf magma.tar.gz
          echo | ./magma/magma

