name: Tests

on:
  push:
    branches: [ '**' ]

  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Create dummy network device
        env:
          MAGMA_MAC: ${{ secrets.MAGMA_MAC }}
        shell: bash
        run: |
          sudo ip link add dumdum type dummy
          sudo ifconfig dumdum hw ether "$MAGMA_MAC"


      - name: Install magma
        env:
          MAGMA_URL: ${{ secrets.MAGMA_URL }}
        shell: bash
        run: |
          wget "$MAGMA_URL" -O magma.tar.gz --quiet
          tar xf magma.tar.gz
          echo | ./magma/magma

      - name: Run tests
        shell: bash
        run: |
          ./magma/magma -b exitsignal:="" run_tests.m

